version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=summer
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql